# Generated by Django 3.2.6 on 2021-08-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_rename_filmes_filme'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='genre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='filme',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='filmes'),
        ),
    ]
