# Generated by Django 3.2.6 on 2021-08-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_auto_20210818_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='genre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
